</div>
				<div id="of_footer">
					<a href="page/alerts">Network Status</a>
					<a href="page/alerts">Foundation</a>
					<a href="page/legal.php">Legal</a>
					<a href="page/about-us.php">About ocpforum.org</a>
					<div id="of_copyright">
						© OCP Project 2011-<?php echo date("Y"); ?> Released under the
						<a href="http://opensource.org/licenses/mit-license.php" target="_blank">MIT license</a>
					</div>
				</div>
			</div>


			<div id="menu1_body" class="of_menu_body">
				<a href="page/individual.php" class="of_menu_item">Individuals</a>
				<a href="page/business.php" class="of_menu_item">Businesses</a>
				<a href="page/developer.php" class="of_menu_item">Developers</a>
				<a href="page/getting-started.php" class="of_menu_item">Getting started</a>
				<a href="page/how-it-works.php" class="of_menu_item">How it works</a>
				<a href="page/you-need-to-know.php" class="menuof_menu_item_item">You need to know</a>
			</div>

			<div id="menu2_body" class="of_menu_body">
				<a href="page/resources.php" class="of_menu_item">Resources</a>
				<a href="page/community.php" class="of_menu_item">Community</a>
				<a href="page/development.php" class="of_menu_item">Development</a>
				<a href="page/vocabulary.php" class="of_menu_item">Vocabulary</a>
				<a href="page/events.php" class="of_menu_item">Events</a>
				<a href="page/press.php" class="of_menu_item">Press</a>
			</div>
		</div>

		<script>
$('#menu1').ocp_menu();
$('#menu2').ocp_menu();
$('#menu3').ocp_menu();
$('#menu4').ocp_menu();
$('#menu5').ocp_menu();
		</script>
	</body>
</html>