</div>
				<div id="of_footer">
					<a href="/en/alerts">Network Status</a>
					<a href="/en/alerts">Foundation</a>
					<a href="page/legal.php">Legal</a>
					<a href="/en/alerts">About bitcoin.org</a>
					<div id="of_copyright">
						© Bitcoin Project 2009-2013 Released under the
						<a href="http://opensource.org/licenses/mit-license.php" target="_blank">MIT license</a>
					</div>
				</div>
			</div>


			<div id="menu1_body" class="of_menu_body">
				<a href="page/individual.php" class="of_menu_item">Individuals</a>
				<a href="page/business.php" class="of_menu_item">Businesses</a>
				<a href="page/developer.php" class="of_menu_item">Developers</a>
				<a href="page/getting_started.php" class="of_menu_item">Getting started</a>
				<a href="page/how-it-works.php" class="of_menu_item">How it works</a>
				<a href="/en/you-need-to-know" class="menuof_menu_item_item">You need to know</a>
			</div>

			<div id="menu2_body" class="of_menu_body">
				<a href="layout/simple.php" class="of_menu_item">Simple</a>
				<a href="layout/table_content.php" class="of_menu_item">Table content</a>
				<a href="layout/two_columns.php" class="of_menu_item">Two columns</a>
				<a href="layout/two_columns_numbered.php" class="of_menu_item">Two columns numbered</a>
				<a href="layout/press.php" class="of_menu_item">Press</a>
			</div>
		</div>

		<script>
$('#menu1').ocp_menu();
$('#menu2').ocp_menu();
$('#menu3').ocp_menu();
$('#menu4').ocp_menu();
$('#menu5').ocp_menu();
		</script>
	</body>
</html>