<!DOCTYPE html>
<html>
	<head>
		<base href="<?php echo BASE_DIR; ?>/" />
		<meta charset="utf-8" />
		<title>OCP Forum</title>
		<link rel="icon" type="image/png" href="image/ocp_logo.png">
		<link rel="stylesheet" href="css/main.css" />

		<script src="_ext/d3.v3.min.js"></script>
		<script src="_ext/sha1.js"></script>

		<!-- JQUERY / JQUERY UI -->
		<script src="_ext/jquery-1.10.2.min.js"></script>
		<script src="_ext/jquery-ui-1.10.3/ui/minified/jquery-ui.min.js"></script>
		<link rel="stylesheet" href="_ext/jquery-ui-1.10.3/themes/base/minified/jquery-ui.min.css" />
		<!-- END JQUERY / JQUERY UI -->

		<script src="_ext/jquery.slides.min.js"></script>
		<script src="_ext/seedrandom-min.js"></script>


		<script src="js/widget_menu.js"></script>
		<link rel="stylesheet" href="js/theme/default/widget_menu.css" />

		<script src="js/widget_content_table.js"></script>
		<link rel="stylesheet" href="js/theme/default/widget_content_table.css" />
	</head>

	<body>
		<div id="of_page">
			<div id="of_header">
				<a href="" id="of_logo">
					<img src="image/logo.png" />
				</a>

				<ul id="of_lang">
					<li><a href="">English</a></li>
					<ul id="of_lang_list">
						<li><a href="">French</a></li>
					</ul>
				</ul>

				<div id="of_menu_bar">
					<div id="menu1" class="of_menu_label">Introduction</div>
					<div id="menu2" class="of_menu_label">Resources</div>
					<div id="menu3" class="of_menu_label"><a href="page/innovation">Innovation</a></div>
					<div id="menu4" class="of_menu_label"><a href="page/donate">Participate</a></div>
					<div id="menu5" class="of_menu_label"><a href="page/faq.php">FAQ</a></div>
				</div>
			</div>

			<div id="of_body">
				<div id="of_content">